### ISSUE TITLE
Photo doesn't appear in photo search

### ISSUE THREAD

**Issue by lauriarnold** [EscherLabs/Graphene#146]
When searching for Ryan Arnold's photo it does not appear

MicroApps, Forms

**To Reproduce**
1. Go to its helpdesk tools http://portalawsdev.binghamton.edu/page/its_helpdesk/ad_tools
2. choose the last tab photo search
3. Enter first name Ryan and last name Arnold
4. 0 results - get a photo back in prod

**Comment by alikemaltanriverdi** [comment]
The microapp mentioned above is: http://portalawsdev.binghamton.edu/app/its_helpdesk/photo_search

@lauriarnold This app was updated in myBinghamton, and it runs as expected in both PROD and portalAWSDev. There might be other issues going on in the API in Hermes, but I do not think that this issue is related to Graphene.

@Cloverstone I believe that this issue can be closed.
