### ISSUE TITLE
New GrapheneForms User Options Doesn't Seem to Save Checkbox Values?

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#17]
I had a checkbox user option, and even though I could make changes, it doesn't appear that I was able to uncheck the checkbox and have that change persist.  

I'm not sure if this is a new behavior specific to the GrapheneForms implementation (I feel like it is), but I ended up switching it to a select with "true"/"false" values.  (I also no longer have an example as I changed it, but I could probably replicate the issue if I had to)

**Comment by timcortesi** [comment]
This is still a confirmed issue.  
See example: 
http://portalawsdev.binghamton.edu/app/ITS/directory_search
http://portalawsdev.binghamton.edu/admin/apps/5

User options has a checkbox called "yes_or_no", but the value doesn't persist.  

1. Click the gear
2. Uncheck the box
3. Refresh the page
4. Click the gear again. 
5. Note that the box value is unchanged
<img width="34" alt="Screen Shot 2020-03-16 at 2 39 11 PM" src="https://user-images.githubusercontent.com/5395437/76789824-0088af80-6794-11ea-9520-214285371d3b.png">
<img width="603" alt="Screen Shot 2020-03-16 at 2 39 17 PM" src="https://user-images.githubusercontent.com/5395437/76789810-f5358400-6793-11ea-9e9d-1ce406904cbe.png">

**Comment by Cloverstone** [comment]
This appears to be because the options object is generated in the builder even if the fields are empty  so the value of "" is equal to the true state which is how its determined, it also happens to match the false state so you never really see a change - you can fix this in the mean time by removing that object manually in the editor or by setting values in the editor for true and false.

The builder will be fixed for this ultimately

**Comment by timcortesi** [comment]
Confirmed working in caf8fd9
